databases:
  - name: hemophilia_nsw_development
    databaseName: hemophilia_nsw_development
    user: postgres
    plan: free

services:
  - type: web
    name: hfnsw_server_new
    runtime: ruby
    plan: free
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec rails server'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hemophilia_nsw_development
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
